import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d4dfde",
        "on-error": "#ffefee",
        "tertiary-dim": "#00557b",
        "surface-container-high": "#dbe4e3",
        "on-primary-fixed": "#004440",
        "error-container": "#fb5151",
        "background": "#f1f8f7",
        "tertiary-fixed": "#40bbff",
        "primary-fixed-dim": "#8cddd6",
        "on-background": "#293030",
        "primary-dim": "#005a55",
        "inverse-on-surface": "#979e9e",
        "primary": "#006762",
        "secondary-container": "#aaefe9",
        "on-surface": "#293030",
        "on-secondary": "#bdfff9",
        "inverse-primary": "#abfdf5",
        "surface": "#f1f8f7",
        "on-secondary-container": "#095c58",
        "error-dim": "#9f0519",
        "inverse-surface": "#090f0f",
        "secondary-fixed-dim": "#9ce1db",
        "surface-container": "#e1eae9",
        "secondary-fixed": "#aaefe9",
        "outline": "#717878",
        "on-primary-container": "#005854",
        "on-tertiary-container": "#00344d",
        "tertiary": "#00628c",
        "error": "#b31b25",
        "primary-fixed": "#9aebe4",
        "on-surface-variant": "#565d5c",
        "on-primary-fixed-variant": "#00635e",
        "on-primary": "#befff8",
        "surface-tint": "#006762",
        "secondary-dim": "#045956",
        "surface-bright": "#f1f8f7",
        "surface-container-low": "#eaf2f1",
        "on-secondary-fixed": "#004844",
        "tertiary-container": "#40bbff",
        "surface-dim": "#cbd7d6",
        "primary-container": "#9aebe4",
        "outline-variant": "#a7afae",
        "tertiary-fixed-dim": "#18adf3",
        "on-error-container": "#570008",
        "on-secondary-fixed-variant": "#1b6662",
        "on-tertiary-fixed": "#001a29",
        "on-tertiary-fixed-variant": "#003d5a",
        "surface-container-highest": "#d4dfde",
        "secondary": "#1b6662",
        "on-tertiary": "#e9f4ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        "glass": "0 20px 40px rgba(0, 72, 68, 0.06)",
        "card": "0 4px 24px rgba(0, 72, 68, 0.04)",
        "elevated": "0 8px 32px rgba(0, 72, 68, 0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
